# Generated by Django 3.2.16 on 2023-01-15 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('maximum_number_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('studentIdentificationNumber', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.school')),
            ],
        ),
    ]
